development: &defaults
  adapter: mysql2
  encoding: utf8
  database: mydb
  username: root
  password:
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: mydb

production:
  <<: *defaults
  database: mydb